CREATE TABLE "GCG_4040_BI_HEAT_RPT"(
 "BIRUNID" BIGINT,
 "PARENT" CHAR(20),
 "PARENT_DESC" CHAR(30),
 "ASSEMBLY" CHAR(20),
 "SORT_PART" CHAR(20),
 "ORD_QTY" NUMERIC(12,4),
 "UM" CHAR(2),
 "MAT_PART" CHAR(20),
 "LOT_PO" CHAR(15),
 "HEAT" CHAR(15),
 "LINK_EXISTS" CHAR(1));
